/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {
    private static final Logger logger = LogManager.getLogger(App.class);
    public String getGreeting() {
        logger.error("Start aplikacji kantor");
        logger.info("GeTgGreeting method called");
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }
}
